# Config values to make Jekyll mimic Github pages as much as possible
safe: true
lsi: false
pygments: true
markdown: redcarpet

# Overall site config
name: "DUBotics"
description: "Robotics club at the University of Washington"
url: "http://dubotics.github.io"
relative: ""

# Blog config
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "blog/page:num"

# Navigation
navigation:
    - title: Home
      url: /index.html
    - title: Blog
      url: /blog.html
      layout: blog-post
    - title: About Us
      url: /about.html
    - title: Our team
      url: /teams.html
    - title: Sponsors
      url: /sponsors.html
    - title: Gallery
      url: /gallery.html
    - title: Resources
      url: /resources.html
    - title: Contact Us
      url: /contact.html
  
# Slideshow config (home page)
carousel:
    images:
        - caption: Team Photo
          url: /assets/past_robots/team-photo.jpg
        - caption: Finished Arm!
          url: /assets/competition_2014/finished-arm.jpg
        - caption: Mars Rover
          url: /assets/competition_2013/full-rover.jpg
        - caption: Quadcopter
          url: /assets/past_robots/quadcopter.jpg
    refresh_rate: 5200
    
# Photo gallery config
gallery:
    - title: "University Rover Competition: 2014 Build"
      images:
        - caption: Machining parts 1
          url: /assets/competition_2014/machining-parts-1.jpg
        - caption: Machining parts 2
          url: /assets/competition_2014/machining-parts-2.jpg
        - caption: Machining parts 3
          url: /assets/competition_2014/machining-parts-3.jpg
        - caption: Drilling
          url: /assets/competition_2014/drilling-1.jpg
        - caption: More drilling
          url: /assets/competition_2014/drilling-2.jpg
        - caption: Chassis Skeleton
          url: /assets/competition_2014/chassis-skeleton.jpg
        - caption: Finished arm!
          url: /assets/competition_2014/finished-arm.jpg
    - title: University Rover Competition (2013)
      images:
        - caption: Robot frame
          url: /assets/competition_2013/robot-frame.jpg
        - caption: The electronics
          url: /assets/competition_2013/electronics.jpg
        - caption: Checking the rover
          url: /assets/competition_2013/checking-the-rover.jpg
        - caption: Last minute fixes
          url: /assets/competition_2013/last-minute.jpg
        - caption: The Cerebus rover
          url: /assets/competition_2013/full-rover.jpg
    - title: Building the Cerebus Rover
      images:
        - caption: Planning the electrical hardware
          url: /assets/building_2013/planning-electronics.jpg
        - caption: Planning the driver interface
          url: /assets/building_2013/driver-interface.jpg
        - caption: Learning to solder
          url: /assets/building_2013/solder.jpg
        - caption: In assembly
          url: /assets/building_2013/cerebus-rover.jpg
        - caption: The control station
          url: /assets/building_2013/control-station.jpg
    - title: Past robots
      images:
        - caption: Quadcopter
          url: /assets/past_robots/quadcopter.jpg
        - caption: Assembling the quadcopter
          url: /assets/past_robots/assembling-quadcopter.jpg
        - caption: Tracker
          url: /assets/past_robots/tracker.jpg
        - caption: Team photo
          url: /assets/past_robots/team-photo.jpg
          
# Meeting times and locations
meeting_times:
    -   team_name: General Meetings
        time: Thu, 6-7pm (biweekly)
        location: MEB 238
        url: http://www.washington.edu/maps/?meb
    -   team_name: Arm
        time: Fri, 5-6:30pm
        location: MEB 238
        url: http://www.washington.edu/maps/?meb
    -   team_name: Control Systems
        time: Sat, 3-4pm
        location: MEB 238
        url: http://www.washington.edu/maps/?meb
        