# Config values to make Jekyll mimic Github pages as much as possible
safe: true
lsi: false
pygments: true
markdown: redcarpet

# Overall site config
name: "DUBotics"
description: "Robotics club at the University of Washington"
url: "http://dubotics.github.io"
relative: ""

# Blog config
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "blog/page:num"

# Navigation
navigation:
    - title: Home
      url: /index.html
    - title: Blog
      url: /blog.html
      layout: blog-post
    - title: About Us
      url: /about.html
    - title: Our team
      url: /teams.html
    - title: Sponsors
      url: /sponsors.html
    - title: Gallery
      url: /gallery.html
    - title: Resources
      url: /resources.html
    - title: Contact Us
      url: /contact.html
  
# Slideshow config (home page)
carousel:
    images:
        - caption: Team Photo
          url: /assets/past_robots/team-photo.jpg
        - caption: Finished Arm!
          url: /assets/competition_2014/finished-arm.jpg
        - caption: Mars Rover
          url: /assets/competition_2013/full-rover.jpg
        - caption: Quadcopter
          url: /assets/past_robots/quadcopter.jpg
    refresh_rate: 5200
    
# Photo gallery config
gallery:
    - title: "University Rover Competition 2014: Crunch-time (Semester 2)"
      images:
        - caption: Fond memories
          url: /assets/competition_2014/fond-memories.jpg
          thumbnail: /assets/competition_2014/thumbnails/fond-memories.jpg
        - caption: It's all greek to me
          url: /assets/competition_2014/greek.jpg
          thumbnail: /assets/competition_2014/thumbnails/greek.jpg
        - caption: Planning
          url: /assets/competition_2014/planning.jpg
          thumbnail: /assets/competition_2014/thumbnails/planning.jpg
        - caption: Planning 2
          url: /assets/competition_2014/planning-2.jpg
          thumbnail: /assets/competition_2014/thumbnails/planning-2.jpg
        - caption: Planning 3
          url: /assets/competition_2014/planning-3.jpg
          thumbnail: /assets/competition_2014/thumbnails/planning-3.jpg
        - caption: Planning 4
          url: /assets/competition_2014/planning-4.jpg
          thumbnail: /assets/competition_2014/thumbnails/planning-4.jpg
        - caption: Planning 5
          url: /assets/competition_2014/planning-5.jpg
          thumbnail: /assets/competition_2014/thumbnails/planning-5.jpg
        - caption: Planning 6
          url: /assets/competition_2014/planning-6.jpg
          thumbnail: /assets/competition_2014/thumbnails/planning-6.jpg
        - caption: Designing the scientific station
          url: /assets/competition_2014/designing-the-scientific-station.jpg
          thumbnail: /assets/competition_2014/thumbnails/designing-the-scientific-station.jpg
        - caption: Designing the electronics board
          url: /assets/competition_2014/designing-electronics-board.jpg
          thumbnail: /assets/competition_2014/thumbnails/designing-electronics-board.jpg
        - caption: Debugging Woes
          url: /assets/competition_2014/debugging-woes.jpg
          thumbnail: /assets/competition_2014/thumbnails/debugging-woes.jpg
        - caption: Smile
          url: /assets/competition_2014/smile.jpg
          thumbnail: /assets/competition_2014/thumbnails/smile.jpg
        - caption: Discussion
          url: /assets/competition_2014/discussion.jpg
          thumbnail: /assets/competition_2014/thumbnails/discussion.jpg
        - caption: Whiteboarding
          url: /assets/competition_2014/whiteboarding.jpg
          thumbnail: /assets/competition_2014/thumbnails/whiteboarding.jpg
        - caption: Raw Stock
          url: /assets/competition_2014/raw-stock.jpg
          thumbnail: /assets/competition_2014/thumbnails/raw-stock.jpg
        - caption: Treads
          url: /assets/competition_2014/treads.jpg
          thumbnail: /assets/competition_2014/thumbnails/treads.jpg
        - caption: CNC Machine 1
          url: /assets/competition_2014/cnc-machine-1.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-1.jpg
        - caption: CNC Machine 2
          url: /assets/competition_2014/cnc-machine-2.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-2.jpg
        - caption: CNC Machine 3
          url: /assets/competition_2014/cnc-machine-3.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-3.jpg
        - caption: CNC Machine 4
          url: /assets/competition_2014/cnc-machine-4.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-4.jpg
        - caption: CNC Machine 5
          url: /assets/competition_2014/cnc-machine-5.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-5.jpg
        - caption: CNC Machine 6
          url: /assets/competition_2014/cnc-machine-6.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-6.jpg
        - caption: CNC Machine 7
          url: /assets/competition_2014/cnc-machine-7.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-7.jpg
        - caption: CNC Machine 8
          url: /assets/competition_2014/cnc-machine-8.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-8.jpg
        - caption: CNC Machine 9
          url: /assets/competition_2014/cnc-machine-9.jpg
          thumbnail: /assets/competition_2014/thumbnails/cnc-machine-9.jpg
        - caption: Components
          url: /assets/competition_2014/components-1.jpg
          thumbnail: /assets/competition_2014/thumbnails/components-1.jpg
        - caption: More components
          url: /assets/competition_2014/components-2.jpg
          thumbnail: /assets/competition_2014/thumbnails/components-2.jpg
        - caption: Welding 1
          url: /assets/competition_2014/welding-1.jpg
          thumbnail: /assets/competition_2014/thumbnails/welding-1.jpg
        - caption: Welding 2
          url: /assets/competition_2014/welding-2.jpg
          thumbnail: /assets/competition_2014/thumbnails/welding-2.jpg
        - caption: Welding 3
          url: /assets/competition_2014/welding-3.jpg
          thumbnail: /assets/competition_2014/thumbnails/welding-3.jpg
        - caption: Welding 4
          url: /assets/competition_2014/welding-4.jpg
          thumbnail: /assets/competition_2014/thumbnails/welding-4.jpg
    
    - title: "University Rover Competition 2014: Beginning to build (Semester 1)"
      images:
        - caption: Machining parts 1
          url: /assets/competition_2014/machining-parts-1.jpg
        - caption: Machining parts 2
          url: /assets/competition_2014/machining-parts-2.jpg
        - caption: Machining parts 3
          url: /assets/competition_2014/machining-parts-3.jpg
        - caption: Drilling
          url: /assets/competition_2014/drilling-1.jpg
        - caption: More drilling
          url: /assets/competition_2014/drilling-2.jpg
        - caption: Chassis Skeleton
          url: /assets/competition_2014/chassis-skeleton.jpg
        - caption: Finished arm!
          url: /assets/competition_2014/finished-arm.jpg
        - caption: Finished arm 2
          url: /assets/competition_2014/finished-arm-2.jpg
        - caption: Arm closeup
          url: /assets/competition_2014/prototype-arm-closeup.jpg
    - title: University Rover Competition (2013)
      images:
        - caption: Robot frame
          url: /assets/competition_2013/robot-frame.jpg
        - caption: The electronics
          url: /assets/competition_2013/electronics.jpg
        - caption: Checking the rover
          url: /assets/competition_2013/checking-the-rover.jpg
        - caption: Last minute fixes
          url: /assets/competition_2013/last-minute.jpg
        - caption: The Cerebus rover
          url: /assets/competition_2013/full-rover.jpg
    - title: Building the Cerebus Rover
      images:
        - caption: Planning the electrical hardware
          url: /assets/building_2013/planning-electronics.jpg
        - caption: Planning the driver interface
          url: /assets/building_2013/driver-interface.jpg
        - caption: Learning to solder
          url: /assets/building_2013/solder.jpg
        - caption: In assembly
          url: /assets/building_2013/cerebus-rover.jpg
        - caption: The control station
          url: /assets/building_2013/control-station.jpg
    - title: Past robots
      images:
        - caption: Quadcopter
          url: /assets/past_robots/quadcopter.jpg
        - caption: Assembling the quadcopter
          url: /assets/past_robots/assembling-quadcopter.jpg
        - caption: Tracker
          url: /assets/past_robots/tracker.jpg
        - caption: Team photo
          url: /assets/past_robots/team-photo.jpg
          
# Meeting times and locations
meeting_times:
    -   team_name: General Meetings
        time: Thu, 6-7pm (biweekly)
        location: MEB 238
        url: http://www.washington.edu/maps/?meb
    -   team_name: Arm
        time: Fri, 5-6:30pm
        location: MEB 238
        url: http://www.washington.edu/maps/?meb
    -   team_name: Control Systems
        time: Sat, 3-4pm
        location: MEB 238
        url: http://www.washington.edu/maps/?meb
        